//Sign up user
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
    "name": "exezz",
    "username": "exezz",
    "password": "qwerty"
}
###

//Sign in user
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
    "username": "exezz",
    "password": "qwerty"
}
###

//Create list
POST http://localhost:8080/api/lists/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU1NjU5MzgsImlhdCI6MTYzNTUyMjczOCwidXNlcl9pZCI6MX0.VkYxAA9jMQzIvv-wsVDYkaO8Jgn32HKoY8S4QoVX3iE
Content-Type: application/json

{
    "title": "about sex",
    "decription": "whaaaaaa"
}
###

//Show all list
GET http://localhost:8080/api/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzYwMDQzMDQsImlhdCI6MTYzNTk2MTEwNCwidXNlcl9pZCI6MX0.8eMRh8R8lClYIHd1TWNLyyBnZDJ6GOif3NYBapyXD74
###

//Get list by id
GET http://localhost:8080/api/lists/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU2Njg4ODYsImlhdCI6MTYzNTYyNTY4NiwidXNlcl9pZCI6MX0.xgvj_KDGdRxETWtwztcAK6y46JHR2cB-yUhPzl_xcxg
###

//Delete list by id
DELETE  http://localhost:8080/api/lists/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU2MjM2MzgsImlhdCI6MTYzNTU4MDQzOCwidXNlcl9pZCI6MX0.g-crLAxBuQAG-dKHyXAtntGH_7gJtF43regYdCRBJpU
###

//Update list by id
PUT http://localhost:8080/api/lists/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU2Njg4ODYsImlhdCI6MTYzNTYyNTY4NiwidXNlcl9pZCI6MX0.xgvj_KDGdRxETWtwztcAK6y46JHR2cB-yUhPzl_xcxg

{
    "title": "about children",
    "description": "aasd"
}
###

//Create item on some list
POST http://localhost:8080/api/lists/3/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzYwMDQzMDQsImlhdCI6MTYzNTk2MTEwNCwidXNlcl9pZCI6MX0.8eMRh8R8lClYIHd1TWNLyyBnZDJ6GOif3NYBapyXD74
Content-Type: application/json

{
    "title": "do REST",
    "description": "handlers u know"
}
###

//Show all items of some list
GET  http://localhost:8080/api/lists/1/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzYwMDQzMDQsImlhdCI6MTYzNTk2MTEwNCwidXNlcl9pZCI6MX0.8eMRh8R8lClYIHd1TWNLyyBnZDJ6GOif3NYBapyXD74
###

//Show items by id
GET  http://localhost:8080/api/items/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzYwODIzNjAsImlhdCI6MTYzNjAzOTE2MCwidXNlcl9pZCI6MX0.8tULgFL5gaMav2UuD_Uzr6SvqqSC8DmD5JTcxRYo35s
###

//Delete by id
DELETE  http://localhost:8080/api/items/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzYwODIzNjAsImlhdCI6MTYzNjAzOTE2MCwidXNlcl9pZCI6MX0.8tULgFL5gaMav2UuD_Uzr6SvqqSC8DmD5JTcxRYo35s
###

//Update by id
PUT  http://localhost:8080/api/items/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzYwODIzNjAsImlhdCI6MTYzNjAzOTE2MCwidXNlcl9pZCI6MX0.8tULgFL5gaMav2UuD_Uzr6SvqqSC8DmD5JTcxRYo35s
Content-Type: application/json

{
    "title": "do SOME",
    "description": "handlers u sex",
    "done": false
}
