POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
    "name": "exezz",
    "username": "exezz",
    "password": "qwerty"
}

###

POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
    "username": "exezz",
    "password": "qwerty"
}

###

POST http://localhost:8080/api/lists
Authorization: Bearer 
###

POST http://localhost:8080/api/lists/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU1NjU5MzgsImlhdCI6MTYzNTUyMjczOCwidXNlcl9pZCI6MX0.VkYxAA9jMQzIvv-wsVDYkaO8Jgn32HKoY8S4QoVX3iE
Content-Type: application/json

{
    "title": "about sex",
    "decription": "whaaaaaa"
}

###

GET http://localhost:8080/api/lists/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU2MjM2MzgsImlhdCI6MTYzNTU4MDQzOCwidXNlcl9pZCI6MX0.g-crLAxBuQAG-dKHyXAtntGH_7gJtF43regYdCRBJpU
###

GET http://localhost:8080/api/lists/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU1NjU5MzgsImlhdCI6MTYzNTUyMjczOCwidXNlcl9pZCI6MX0.VkYxAA9jMQzIvv-wsVDYkaO8Jgn32HKoY8S4QoVX3iE

###
DELETE  http://localhost:8080/api/lists/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU2MjM2MzgsImlhdCI6MTYzNTU4MDQzOCwidXNlcl9pZCI6MX0.g-crLAxBuQAG-dKHyXAtntGH_7gJtF43regYdCRBJpU

